/**
 * Autogenerated by Thrift Compiler (0.10.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.message.thrift.actor.world;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-08-29")
public class UserReconnectionTry implements org.apache.thrift.TBase<UserReconnectionTry, UserReconnectionTry._Fields>, java.io.Serializable, Cloneable, Comparable<UserReconnectionTry> {
    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserReconnectionTry");
    private static final org.apache.thrift.protocol.TField RE_BIND_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("reBindKey", org.apache.thrift.protocol.TType.STRING, (short) 1);
    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new UserReconnectionTryStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new UserReconnectionTryTupleSchemeFactory();

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.RE_BIND_KEY, new org.apache.thrift.meta_data.FieldMetaData("reBindKey", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserReconnectionTry.class, metaDataMap);
    }

    public java.lang.String reBindKey; // required

    public UserReconnectionTry() {
    }

    public UserReconnectionTry(
            java.lang.String reBindKey) {
        this();
        this.reBindKey = reBindKey;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public UserReconnectionTry(UserReconnectionTry other) {
        if (other.isSetReBindKey()) {
            this.reBindKey = other.reBindKey;
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }

    public UserReconnectionTry deepCopy() {
        return new UserReconnectionTry(this);
    }

    @Override
    public void clear() {
        this.reBindKey = null;
    }

    public java.lang.String getReBindKey() {
        return this.reBindKey;
    }

    public UserReconnectionTry setReBindKey(java.lang.String reBindKey) {
        this.reBindKey = reBindKey;
        return this;
    }

    public void unsetReBindKey() {
        this.reBindKey = null;
    }

    /** Returns true if field reBindKey is set (has been assigned a value) and false otherwise */
    public boolean isSetReBindKey() {
        return this.reBindKey != null;
    }

    public void setReBindKeyIsSet(boolean value) {
        if (!value) {
            this.reBindKey = null;
        }
    }

    public void setFieldValue(_Fields field, java.lang.Object value) {
        switch (field) {
            case RE_BIND_KEY:
                if (value == null) {
                    unsetReBindKey();
                } else {
                    setReBindKey((java.lang.String) value);
                }
                break;

        }
    }

    public java.lang.Object getFieldValue(_Fields field) {
        switch (field) {
            case RE_BIND_KEY:
                return getReBindKey();

        }
        throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new java.lang.IllegalArgumentException();
        }

        switch (field) {
            case RE_BIND_KEY:
                return isSetReBindKey();
        }
        throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
        if (that == null)
            return false;
        if (that instanceof UserReconnectionTry)
            return this.equals((UserReconnectionTry) that);
        return false;
    }

    public boolean equals(UserReconnectionTry that) {
        if (that == null)
            return false;
        if (this == that)
            return true;

        boolean this_present_reBindKey = true && this.isSetReBindKey();
        boolean that_present_reBindKey = true && that.isSetReBindKey();
        if (this_present_reBindKey || that_present_reBindKey) {
            if (!(this_present_reBindKey && that_present_reBindKey))
                return false;
            if (!this.reBindKey.equals(that.reBindKey))
                return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetReBindKey()) ? 131071 : 524287);
        if (isSetReBindKey())
            hashCode = hashCode * 8191 + reBindKey.hashCode();

        return hashCode;
    }

    @Override
    public int compareTo(UserReconnectionTry other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = java.lang.Boolean.valueOf(isSetReBindKey()).compareTo(other.isSetReBindKey());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetReBindKey()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reBindKey, other.reBindKey);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder("UserReconnectionTry(");
        boolean first = true;

        sb.append("reBindKey:");
        if (this.reBindKey == null) {
            sb.append("null");
        } else {
            sb.append(this.reBindKey);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        RE_BIND_KEY((short) 1, "reBindKey");

        private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        private final short _thriftId;
        private final java.lang.String _fieldName;

        _Fields(short thriftId, java.lang.String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // RE_BIND_KEY
                    return RE_BIND_KEY;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        public static _Fields findByName(java.lang.String name) {
            return byName.get(name);
        }

        public short getThriftFieldId() {
            return _thriftId;
        }

        public java.lang.String getFieldName() {
            return _fieldName;
        }
    }

    private static class UserReconnectionTryStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        public UserReconnectionTryStandardScheme getScheme() {
            return new UserReconnectionTryStandardScheme();
        }
    }

    private static class UserReconnectionTryStandardScheme extends org.apache.thrift.scheme.StandardScheme<UserReconnectionTry> {

        public void read(org.apache.thrift.protocol.TProtocol iprot, UserReconnectionTry struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // RE_BIND_KEY
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.reBindKey = iprot.readString();
                            struct.setReBindKeyIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot, UserReconnectionTry struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.reBindKey != null) {
                oprot.writeFieldBegin(RE_BIND_KEY_FIELD_DESC);
                oprot.writeString(struct.reBindKey);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class UserReconnectionTryTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        public UserReconnectionTryTupleScheme getScheme() {
            return new UserReconnectionTryTupleScheme();
        }
    }

    private static class UserReconnectionTryTupleScheme extends org.apache.thrift.scheme.TupleScheme<UserReconnectionTry> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, UserReconnectionTry struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetReBindKey()) {
                optionals.set(0);
            }
            oprot.writeBitSet(optionals, 1);
            if (struct.isSetReBindKey()) {
                oprot.writeString(struct.reBindKey);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, UserReconnectionTry struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(1);
            if (incoming.get(0)) {
                struct.reBindKey = iprot.readString();
                struct.setReBindKeyIsSet(true);
            }
        }
    }
}

