/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.message.thrift.actor.area;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-09-20")
public class RemoveGrid implements org.apache.thrift.TBase<RemoveGrid, RemoveGrid._Fields>, java.io.Serializable, Cloneable, Comparable<RemoveGrid> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RemoveGrid");

  private static final org.apache.thrift.protocol.TField GRID_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("gridId", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RemoveGridStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RemoveGridTupleSchemeFactory();

  public java.lang.String gridId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    GRID_ID((short)1, "gridId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // GRID_ID
          return GRID_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.GRID_ID, new org.apache.thrift.meta_data.FieldMetaData("gridId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RemoveGrid.class, metaDataMap);
  }

  public RemoveGrid() {
  }

  public RemoveGrid(
    java.lang.String gridId)
  {
    this();
    this.gridId = gridId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RemoveGrid(RemoveGrid other) {
    if (other.isSetGridId()) {
      this.gridId = other.gridId;
    }
  }

  public RemoveGrid deepCopy() {
    return new RemoveGrid(this);
  }

  @Override
  public void clear() {
    this.gridId = null;
  }

  public java.lang.String getGridId() {
    return this.gridId;
  }

  public RemoveGrid setGridId(java.lang.String gridId) {
    this.gridId = gridId;
    return this;
  }

  public void unsetGridId() {
    this.gridId = null;
  }

  /** Returns true if field gridId is set (has been assigned a value) and false otherwise */
  public boolean isSetGridId() {
    return this.gridId != null;
  }

  public void setGridIdIsSet(boolean value) {
    if (!value) {
      this.gridId = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case GRID_ID:
      if (value == null) {
        unsetGridId();
      } else {
        setGridId((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case GRID_ID:
      return getGridId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case GRID_ID:
      return isSetGridId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof RemoveGrid)
      return this.equals((RemoveGrid)that);
    return false;
  }

  public boolean equals(RemoveGrid that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_gridId = true && this.isSetGridId();
    boolean that_present_gridId = true && that.isSetGridId();
    if (this_present_gridId || that_present_gridId) {
      if (!(this_present_gridId && that_present_gridId))
        return false;
      if (!this.gridId.equals(that.gridId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetGridId()) ? 131071 : 524287);
    if (isSetGridId())
      hashCode = hashCode * 8191 + gridId.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(RemoveGrid other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetGridId()).compareTo(other.isSetGridId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGridId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gridId, other.gridId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RemoveGrid(");
    boolean first = true;

    sb.append("gridId:");
    if (this.gridId == null) {
      sb.append("null");
    } else {
      sb.append(this.gridId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RemoveGridStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RemoveGridStandardScheme getScheme() {
      return new RemoveGridStandardScheme();
    }
  }

  private static class RemoveGridStandardScheme extends org.apache.thrift.scheme.StandardScheme<RemoveGrid> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RemoveGrid struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // GRID_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.gridId = iprot.readString();
              struct.setGridIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RemoveGrid struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.gridId != null) {
        oprot.writeFieldBegin(GRID_ID_FIELD_DESC);
        oprot.writeString(struct.gridId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RemoveGridTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RemoveGridTupleScheme getScheme() {
      return new RemoveGridTupleScheme();
    }
  }

  private static class RemoveGridTupleScheme extends org.apache.thrift.scheme.TupleScheme<RemoveGrid> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RemoveGrid struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetGridId()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetGridId()) {
        oprot.writeString(struct.gridId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RemoveGrid struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.gridId = iprot.readString();
        struct.setGridIdIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

