// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonMessage.proto

package com.codebroker.demo.protobuf.common;

public final class CommonMessage {
  private CommonMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Creates_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Creates_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Updates_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Updates_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Deletes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Deletes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseCommon_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseCommon_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023CommonMessage.proto\"\t\n\007Creates\"\t\n\007Upda" +
      "tes\"\t\n\007Deletes\"n\n\016ResponseCommon\022\013\n\003cmd\030" +
      "\001 \001(\005\022\031\n\007creates\030\002 \001(\0132\010.Creates\022\031\n\007upda" +
      "tes\030\003 \001(\0132\010.Updates\022\031\n\007deletes\030\004 \001(\0132\010.D" +
      "eletesB\'\n#com.codebroker.demo.protobuf.c" +
      "ommonP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Creates_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Creates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Creates_descriptor,
        new java.lang.String[] { });
    internal_static_Updates_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Updates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Updates_descriptor,
        new java.lang.String[] { });
    internal_static_Deletes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Deletes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Deletes_descriptor,
        new java.lang.String[] { });
    internal_static_ResponseCommon_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ResponseCommon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseCommon_descriptor,
        new java.lang.String[] { "Cmd", "Creates", "Updates", "Deletes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
