// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonMessage.proto

package com.codebroker.demo.protobuf.common;

public interface UpdatesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Updates)
    com.google.protobuf.MessageOrBuilder {
}
