// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AllianceMessage.proto

package com.codebroker.protobuff.alliance;

public interface CreateAllianceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateAllianceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 status = 1;</code>
   * @return The status.
   */
  long getStatus();
}
