// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonMessage.proto

package com.codebroker.protobuff.common;

public interface ResponseCommonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseCommon)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 cmd = 1;</code>
   * @return The cmd.
   */
  int getCmd();

  /**
   * <code>.Creates creates = 2;</code>
   * @return Whether the creates field is set.
   */
  boolean hasCreates();
  /**
   * <code>.Creates creates = 2;</code>
   * @return The creates.
   */
  com.codebroker.protobuff.common.Creates getCreates();
  /**
   * <code>.Creates creates = 2;</code>
   */
  com.codebroker.protobuff.common.CreatesOrBuilder getCreatesOrBuilder();

  /**
   * <code>.Updates updates = 3;</code>
   * @return Whether the updates field is set.
   */
  boolean hasUpdates();
  /**
   * <code>.Updates updates = 3;</code>
   * @return The updates.
   */
  com.codebroker.protobuff.common.Updates getUpdates();
  /**
   * <code>.Updates updates = 3;</code>
   */
  com.codebroker.protobuff.common.UpdatesOrBuilder getUpdatesOrBuilder();

  /**
   * <code>.Deletes deletes = 4;</code>
   * @return Whether the deletes field is set.
   */
  boolean hasDeletes();
  /**
   * <code>.Deletes deletes = 4;</code>
   * @return The deletes.
   */
  com.codebroker.protobuff.common.Deletes getDeletes();
  /**
   * <code>.Deletes deletes = 4;</code>
   */
  com.codebroker.protobuff.common.DeletesOrBuilder getDeletesOrBuilder();
}
