// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonMessage.proto

package com.codebroker.protobuff.common;

public interface DeletesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Deletes)
    com.google.protobuf.MessageOrBuilder {
}
