// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemMessage.proto

package com.codebroker.protobuff.item;

public interface BuyItemRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BuyItemRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 itemId = 1;</code>
   * @return The itemId.
   */
  int getItemId();
}
