// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemMessage.proto

package com.codebroker.protobuff.item;

public interface ItemBeanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ItemBean)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 itemId = 1;</code>
   * @return The itemId.
   */
  int getItemId();

  /**
   * <code>int32 itemCount = 2;</code>
   * @return The itemCount.
   */
  int getItemCount();
}
