// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonMessage.proto

package com.codebroker.protobuff.common;

public interface CreatesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Creates)
    com.google.protobuf.MessageOrBuilder {
}
