// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessage.proto

package com.codebroker.protobuf;

public interface Login_COrBuilder extends
    // @@protoc_insertion_point(interface_extends:Login_C)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 protoId = 1;</code>
   * @return The protoId.
   */
  int getProtoId();

  /**
   * <code>string openId = 2;</code>
   * @return The openId.
   */
  String getOpenId();
  /**
   * <code>string openId = 2;</code>
   * @return The bytes for openId.
   */
  com.google.protobuf.ByteString
      getOpenIdBytes();

  /**
   * <code>int64 uid = 3;</code>
   * @return The uid.
   */
  long getUid();

  /**
   * <code>string version = 4;</code>
   * @return The version.
   */
  String getVersion();
  /**
   * <code>string version = 4;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string deviceId = 5;</code>
   * @return The deviceId.
   */
  String getDeviceId();
  /**
   * <code>string deviceId = 5;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string serverName = 6;</code>
   * @return The serverName.
   */
  String getServerName();
  /**
   * <code>string serverName = 6;</code>
   * @return The bytes for serverName.
   */
  com.google.protobuf.ByteString
      getServerNameBytes();
}
