// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginMessage.proto

package com.codebroker.demo.protobuf.login;

public interface AccountRegisterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccountRegisterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 protoId = 1;</code>
   * @return The protoId.
   */
  int getProtoId();

  /**
   * <code>string uid = 2;</code>
   * @return The uid.
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 2;</code>
   * @return The bytes for uid.
   */
  com.google.protobuf.ByteString
      getUidBytes();
}
