// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginMessage.proto

package com.codebroker.demo.protobuf.login;

public final class LoginMessage {
  private LoginMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccountRegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccountRegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccountRegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccountRegisterResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022LoginMessage.proto\"s\n\014LoginRequest\022\017\n\007" +
      "protoId\030\001 \001(\005\022\016\n\006openId\030\002 \001(\t\022\013\n\003uid\030\003 \001" +
      "(\003\022\017\n\007version\030\004 \001(\t\022\020\n\010deviceId\030\005 \001(\t\022\022\n" +
      "\nserverName\030\006 \001(\t\" \n\rLoginResponse\022\017\n\007pr" +
      "otoId\030\001 \001(\005\"}\n\026AccountRegisterRequest\022\017\n" +
      "\007protoId\030\001 \001(\005\022\016\n\006openId\030\002 \001(\t\022\013\n\003uid\030\003 " +
      "\001(\003\022\017\n\007version\030\004 \001(\t\022\020\n\010deviceId\030\005 \001(\t\022\022" +
      "\n\nserverName\030\006 \001(\t\"7\n\027AccountRegisterRes" +
      "ponse\022\017\n\007protoId\030\001 \001(\005\022\013\n\003uid\030\002 \001(\tB&\n\"c" +
      "om.codebroker.demo.protobuf.loginP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRequest_descriptor,
        new java.lang.String[] { "ProtoId", "OpenId", "Uid", "Version", "DeviceId", "ServerName", });
    internal_static_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginResponse_descriptor,
        new java.lang.String[] { "ProtoId", });
    internal_static_AccountRegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AccountRegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccountRegisterRequest_descriptor,
        new java.lang.String[] { "ProtoId", "OpenId", "Uid", "Version", "DeviceId", "ServerName", });
    internal_static_AccountRegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AccountRegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccountRegisterResponse_descriptor,
        new java.lang.String[] { "ProtoId", "Uid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
