// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginMessage.proto

package com.codebroker.demo.protobuf.login;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 protoId = 1;</code>
   * @return The protoId.
   */
  int getProtoId();
}
