// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AllianceMessage.proto

package com.codebroker.protobuff.alliance;

public final class AllianceMessage {
  private AllianceMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateAllianceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateAllianceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateAllianceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateAllianceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025AllianceMessage.proto\"%\n\025CreateAllianc" +
      "eRequest\022\014\n\004name\030\001 \001(\t\"(\n\026CreateAlliance" +
      "Response\022\016\n\006status\030\001 \001(\003B%\n!com.codebrok" +
      "er.protobuff.allianceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CreateAllianceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateAllianceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateAllianceRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_CreateAllianceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CreateAllianceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateAllianceResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
