// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemMessage.proto

package com.codebroker.demo.protobuf.item;

public final class ItemMessage {
  private ItemMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ItemBean_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ItemBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ItemMessage.proto\032\022LoginMessage.proto\"" +
      "-\n\010ItemBean\022\016\n\006itemId\030\001 \001(\005\022\021\n\titemCount" +
      "\030\002 \001(\005B%\n!com.codebroker.demo.protobuf.i" +
      "temP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.codebroker.demo.protobuf.login.LoginMessage.getDescriptor(),
        });
    internal_static_ItemBean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ItemBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ItemBean_descriptor,
        new java.lang.String[] { "ItemId", "ItemCount", });
    com.codebroker.demo.protobuf.login.LoginMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
